### ISSUE TITLE
Fan_always_on issue when importing

### ISSUE THREAD

**Issue by morrowsend** [jjaeggli/prusaslicer-lulzbot-taz#2]
When I tried to import into PrusaSlicer 2.3.3, it gave the error that fan_always_on values were out of spec and wouldn't load. I edited lines  327 and 344 to both say "fan_always_on = 1" and everything else loaded fine.

**Comment by TimWilde** [comment]
Created a PR (#4) that replaces this with `fan_full_speed_layer` which _should_ maintain the original meaning... I think.

**Comment by jjaeggli** [comment]
This has been tested and verified with PrusaSlicer 2.5.0. I've added `fan_always_on = 0` to the generic material, which is also the default.
